name: Configuration development module - multiple import mod
type: module
description: 'Helps developers work with configuration.'
package: Configuration
# version: VERSION
# core: 8.x
configure: config_devel_import_multiple.settings

# Information added by Drupal.org packaging script on 2016-06-21
version: '8.x-0.1-dev'
core: '8.x'
project: 'config_devel_import_multiple'
datestamp: 1466497440
